import { randomUUID } from "node:crypto";
import { db } from "./database";
import type { AnalyticsSnapshot, Recommendation } from "@/domain/analytics";

type SnapshotRow = {id:string;project_id:string;youtube_video_id:string|null;window_hours:number;captured_at:string;source:"demo"|"youtube";views:number;estimated_minutes_watched:number;average_view_duration:number;average_view_percentage:number;subscribers_gained:number;likes:number;comments:number;impressions:number|null;impression_ctr:number|null};
const mapSnapshot=(r:SnapshotRow):AnalyticsSnapshot=>({id:r.id,projectId:r.project_id,youtubeVideoId:r.youtube_video_id,windowHours:r.window_hours as AnalyticsSnapshot["windowHours"],capturedAt:r.captured_at,source:r.source,views:r.views,estimatedMinutesWatched:r.estimated_minutes_watched,averageViewDuration:r.average_view_duration,averageViewPercentage:r.average_view_percentage,subscribersGained:r.subscribers_gained,likes:r.likes,comments:r.comments,impressions:r.impressions,impressionCtr:r.impression_ctr});
export function listAnalyticsSnapshots(projectId:string){return(db.prepare("SELECT * FROM analytics_snapshots WHERE project_id=? ORDER BY window_hours").all(projectId) as SnapshotRow[]).map(mapSnapshot)}
export function saveAnalyticsSnapshot(input:Omit<AnalyticsSnapshot,"id"|"capturedAt">){const id=randomUUID(),capturedAt=new Date().toISOString();db.prepare(`INSERT INTO analytics_snapshots VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(project_id,window_hours) DO UPDATE SET youtube_video_id=excluded.youtube_video_id,captured_at=excluded.captured_at,source=excluded.source,views=excluded.views,estimated_minutes_watched=excluded.estimated_minutes_watched,average_view_duration=excluded.average_view_duration,average_view_percentage=excluded.average_view_percentage,subscribers_gained=excluded.subscribers_gained,likes=excluded.likes,comments=excluded.comments,impressions=excluded.impressions,impression_ctr=excluded.impression_ctr`).run(id,input.projectId,input.youtubeVideoId,input.windowHours,capturedAt,input.source,input.views,input.estimatedMinutesWatched,input.averageViewDuration,input.averageViewPercentage,input.subscribersGained,input.likes,input.comments,input.impressions,input.impressionCtr);return listAnalyticsSnapshots(input.projectId).find(s=>s.windowHours===input.windowHours)!}
type RecommendationRow={id:string;project_id:string;category:Recommendation["category"];finding:string;recommendation:string;confidence:Recommendation["confidence"];evidence_json:string;status:Recommendation["status"];created_at:string};
const mapRecommendation=(r:RecommendationRow):Recommendation=>({id:r.id,projectId:r.project_id,category:r.category,finding:r.finding,recommendation:r.recommendation,confidence:r.confidence,evidence:JSON.parse(r.evidence_json) as Recommendation["evidence"],status:r.status,createdAt:r.created_at});
export function listRecommendations(projectId:string){return(db.prepare("SELECT * FROM performance_recommendations WHERE project_id=? ORDER BY created_at DESC").all(projectId) as RecommendationRow[]).map(mapRecommendation)}
export function replaceProposedRecommendations(projectId:string,items:Omit<Recommendation,"id"|"projectId"|"status"|"createdAt">[]){db.prepare("DELETE FROM performance_recommendations WHERE project_id=? AND status='PROPOSED'").run(projectId);const insert=db.prepare("INSERT INTO performance_recommendations VALUES (?,?,?,?,?,?,?,?,?)"),now=new Date().toISOString();for(const item of items)insert.run(randomUUID(),projectId,item.category,item.finding,item.recommendation,item.confidence,JSON.stringify(item.evidence),"PROPOSED",now)}
export function decideRecommendation(projectId:string,id:string,status:"APPROVED"|"REJECTED"){const result=db.prepare("UPDATE performance_recommendations SET status=? WHERE id=? AND project_id=? AND status='PROPOSED'").run(status,id,projectId);if(result.changes!==1)throw new Error("Recommendation is not available for review")}
