import { randomUUID } from "node:crypto";
import { db } from "./database.ts";

export type PublicationRecord={projectId:string;mode:"demo"|"youtube";selectedThumbnail:string;privacyStatus:string;scheduledAt:string|null;publishedAt:string|null;reconciledAt:string|null;createdAt:string;updatedAt:string};
type Row={project_id:string;mode:"demo"|"youtube";selected_thumbnail:string;privacy_status:string;scheduled_at:string|null;published_at:string|null;reconciled_at:string|null;created_at:string;updated_at:string};
const map=(r:Row):PublicationRecord=>({projectId:r.project_id,mode:r.mode,selectedThumbnail:r.selected_thumbnail,privacyStatus:r.privacy_status,scheduledAt:r.scheduled_at,publishedAt:r.published_at,reconciledAt:r.reconciled_at,createdAt:r.created_at,updatedAt:r.updated_at});
export function getPublication(projectId:string){const row=db.prepare("SELECT * FROM publication_records WHERE project_id=?").get(projectId) as Row|undefined;return row?map(row):null}
export function savePublication(projectId:string,input:Partial<Pick<PublicationRecord,"mode"|"selectedThumbnail"|"privacyStatus"|"scheduledAt"|"publishedAt"|"reconciledAt">>){const prior=getPublication(projectId),now=new Date().toISOString(),record:PublicationRecord={projectId,mode:input.mode??prior?.mode??"demo",selectedThumbnail:input.selectedThumbnail??prior?.selectedThumbnail??"thumbnail-a.svg",privacyStatus:input.privacyStatus??prior?.privacyStatus??"private",scheduledAt:input.scheduledAt===undefined?prior?.scheduledAt??null:input.scheduledAt,publishedAt:input.publishedAt===undefined?prior?.publishedAt??null:input.publishedAt,reconciledAt:input.reconciledAt===undefined?prior?.reconciledAt??null:input.reconciledAt,createdAt:prior?.createdAt??now,updatedAt:now};db.prepare(`INSERT INTO publication_records VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(project_id) DO UPDATE SET mode=excluded.mode,selected_thumbnail=excluded.selected_thumbnail,privacy_status=excluded.privacy_status,scheduled_at=excluded.scheduled_at,published_at=excluded.published_at,reconciled_at=excluded.reconciled_at,updated_at=excluded.updated_at`).run(record.projectId,record.mode,record.selectedThumbnail,record.privacyStatus,record.scheduledAt,record.publishedAt,record.reconciledAt,record.createdAt,record.updatedAt);return record}
export function createExperiment(projectId:string,recommendationId:string,hypothesis:string,variable:string){const now=new Date().toISOString();db.prepare("INSERT INTO experiments (id, project_id, recommendation_id, hypothesis, variable, status, started_at, completed_at, result, created_at) VALUES (?,?,?,?,?, 'PLANNED', NULL,NULL,NULL,?)").run(randomUUID(),projectId,recommendationId,hypothesis,variable,now)}
export function listExperiments(projectId:string){return db.prepare("SELECT * FROM experiments WHERE project_id=? ORDER BY created_at DESC").all(projectId) as Array<{id:string;hypothesis:string;variable:string;status:string;started_at:string|null;completed_at:string|null;result:string|null}>}
