import { randomUUID } from "node:crypto";
import { db } from "./database";

export type ResearchSource={id:string;title:string;url:string;publisher:string;publishedAt:string|null;accessedAt:string;trustLevel:"PRIMARY"|"HIGH"|"MEDIUM"|"LOW";notes:string};
export type Claim={id:string;claimText:string;sourceId:string|null;supportStatus:"SUPPORTED"|"PARTIAL"|"UNSUPPORTED"|"STALE";riskLevel:"LOW"|"MEDIUM"|"HIGH";evidence:string;asOfDate:string|null;createdAt:string};
export function addSource(projectId:string,input:Omit<ResearchSource,"id"|"accessedAt">):ResearchSource{const item={id:randomUUID(),accessedAt:new Date().toISOString(),...input};db.prepare("INSERT INTO research_sources VALUES (?,?,?,?,?,?,?,?,?)").run(item.id,projectId,item.title,item.url,item.publisher,item.publishedAt,item.accessedAt,item.trustLevel,item.notes);return item;}
export function listSources(projectId:string):ResearchSource[]{return(db.prepare("SELECT * FROM research_sources WHERE project_id=? ORDER BY accessed_at DESC").all(projectId)as Record<string,unknown>[]).map(r=>({id:r.id as string,title:r.title as string,url:r.url as string,publisher:r.publisher as string,publishedAt:r.published_at as string|null,accessedAt:r.accessed_at as string,trustLevel:r.trust_level as ResearchSource["trustLevel"],notes:r.notes as string}));}
export function addClaim(projectId:string,input:Omit<Claim,"id"|"createdAt">):Claim{if(input.sourceId){const source=db.prepare("SELECT id FROM research_sources WHERE id=? AND project_id=?").get(input.sourceId,projectId);if(!source)throw new Error("Source not found");}const item={id:randomUUID(),createdAt:new Date().toISOString(),...input};db.prepare("INSERT INTO claims VALUES (?,?,?,?,?,?,?,?,?)").run(item.id,projectId,item.claimText,item.sourceId,item.supportStatus,item.riskLevel,item.evidence,item.asOfDate,item.createdAt);return item;}
export function listClaims(projectId:string):Claim[]{return(db.prepare("SELECT * FROM claims WHERE project_id=? ORDER BY created_at DESC").all(projectId)as Record<string,unknown>[]).map(r=>({id:r.id as string,claimText:r.claim_text as string,sourceId:r.source_id as string|null,supportStatus:r.support_status as Claim["supportStatus"],riskLevel:r.risk_level as Claim["riskLevel"],evidence:r.evidence as string,asOfDate:r.as_of_date as string|null,createdAt:r.created_at as string}));}
export function clearResearch(projectId:string){db.exec("BEGIN IMMEDIATE");try{db.prepare("DELETE FROM claims WHERE project_id=?").run(projectId);db.prepare("DELETE FROM research_sources WHERE project_id=?").run(projectId);db.exec("COMMIT")}catch(error){db.exec("ROLLBACK");throw error}}
