import {createCipheriv,createDecipheriv,randomBytes} from "node:crypto";
import {db} from "./database";
const scope=["https://www.googleapis.com/auth/youtube.upload","https://www.googleapis.com/auth/youtube.readonly","https://www.googleapis.com/auth/yt-analytics.readonly"].join(" ");
const config=()=>({clientId:process.env.GOOGLE_CLIENT_ID,clientSecret:process.env.GOOGLE_CLIENT_SECRET,redirectUri:process.env.GOOGLE_REDIRECT_URI??"http://localhost:3000/api/youtube/oauth/callback",key:process.env.YOUTUBE_TOKEN_ENCRYPTION_KEY});
const key=()=>{const value=config().key;if(!value)throw new Error("YOUTUBE_TOKEN_ENCRYPTION_KEY is required");const b=Buffer.from(value,"base64");if(b.length!==32)throw new Error("Token encryption key must be 32 bytes in base64");return b;};
const encrypt=(text:string)=>{const iv=randomBytes(12),cipher=createCipheriv("aes-256-gcm",key(),iv),body=Buffer.concat([cipher.update(text,"utf8"),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),body]).toString("base64")};
const decrypt=(text:string)=>{const b=Buffer.from(text,"base64"),d=createDecipheriv("aes-256-gcm",key(),b.subarray(0,12));d.setAuthTag(b.subarray(12,28));return Buffer.concat([d.update(b.subarray(28)),d.final()]).toString("utf8")};
export const youtubeConfigured=()=>!!(config().clientId&&config().clientSecret&&config().key);
export function authorizationUrl(state:string){const c=config();if(!c.clientId)throw new Error("GOOGLE_CLIENT_ID is required");const q=new URLSearchParams({client_id:c.clientId,redirect_uri:c.redirectUri,response_type:"code",scope,access_type:"offline",prompt:"consent",include_granted_scopes:"true",state});return`https://accounts.google.com/o/oauth2/v2/auth?${q}`;}
export async function exchangeCode(code:string){const c=config();if(!c.clientId||!c.clientSecret)throw new Error("Google OAuth is not configured");const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({code,client_id:c.clientId,client_secret:c.clientSecret,redirect_uri:c.redirectUri,grant_type:"authorization_code"})});if(!r.ok)throw new Error(`OAuth token exchange failed (${r.status})`);const t=await r.json() as {access_token:string;refresh_token?:string;expires_in:number;scope:string};if(!t.refresh_token)throw new Error("Google did not return an offline refresh token");const now=new Date().toISOString(),expires=new Date(Date.now()+t.expires_in*1000).toISOString();db.prepare("INSERT OR REPLACE INTO youtube_connections VALUES ('default',?,?,?,?,?)").run(encrypt(t.access_token),encrypt(t.refresh_token),expires,t.scope,now);}
export function connectionStatus(){const r=db.prepare("SELECT expires_at,scope,connected_at FROM youtube_connections WHERE id='default'").get() as {expires_at:string;scope:string;connected_at:string}|undefined;return{configured:youtubeConfigured(),connected:!!r,expiresAt:r?.expires_at??null,scope:r?.scope??null,connectedAt:r?.connected_at??null};}
export async function disconnectYouTube(){try{const token=await accessToken();await fetch(`https://oauth2.googleapis.com/revoke?token=${encodeURIComponent(token)}`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"}});}catch{}finally{db.prepare("DELETE FROM youtube_connections WHERE id='default'").run();}}
export async function accessToken(){const r=db.prepare("SELECT * FROM youtube_connections WHERE id='default'").get() as Record<string,string>|undefined;if(!r)throw new Error("YouTube is not connected");if(Date.parse(r.expires_at)>Date.now()+60_000)return decrypt(r.access_token);const c=config();const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:c.clientId!,client_secret:c.clientSecret!,refresh_token:decrypt(r.refresh_token),grant_type:"refresh_token"})});if(!response.ok)throw new Error(`Token refresh failed (${response.status})`);const t=await response.json() as {access_token:string;expires_in:number};db.prepare("UPDATE youtube_connections SET access_token=?,expires_at=? WHERE id='default'").run(encrypt(t.access_token),new Date(Date.now()+t.expires_in*1000).toISOString());return t.access_token;}
