import { createHash } from "node:crypto";
import { accessToken } from "@/infrastructure/youtube-auth";
import { getUpload } from "./youtube-uploader";
import {connectionStatus} from "@/infrastructure/youtube-auth";
import { validateSnapshot, type AnalyticsSnapshot, type AnalyticsWindow } from "@/domain/analytics";

type SnapshotInput=Omit<AnalyticsSnapshot,"id"|"capturedAt">;
const seed=(value:string)=>parseInt(createHash("sha256").update(value).digest("hex").slice(0,8),16);
function demo(projectId:string,windowHours:AnalyticsWindow):SnapshotInput{const n=seed(projectId),factor=windowHours/24,views=Math.round((90+n%260)*Math.pow(factor,.72)),ctr=Number((2.8+(n%38)/10).toFixed(1)),percentage=Number((28+(n%28)).toFixed(1));return validateSnapshot({projectId,youtubeVideoId:getUpload(projectId)?.youtubeVideoId??null,windowHours,source:"demo",views,estimatedMinutesWatched:Number((views*(2.2+(n%25)/10)).toFixed(1)),averageViewDuration:Math.round(95+(n%190)),averageViewPercentage:percentage,subscribersGained:Math.round(views*((n%8)+1)/1000),likes:Math.round(views*(.025+(n%40)/1000)),comments:Math.round(views*(.002+(n%8)/1000)),impressions:Math.round(views/(ctr/100)),impressionCtr:ctr});}
function isoDate(daysAgo:number){const d=new Date(Date.now()-daysAgo*86400000);return d.toISOString().slice(0,10)}
async function youtube(projectId:string,windowHours:AnalyticsWindow):Promise<SnapshotInput>{const videoId=getUpload(projectId)?.youtubeVideoId;if(!videoId)throw new Error("No uploaded YouTube video is recorded for this project");const q=new URLSearchParams({ids:"channel==MINE",startDate:isoDate(Math.max(1,Math.ceil(windowHours/24))),endDate:isoDate(0),metrics:"views,estimatedMinutesWatched,averageViewDuration,averageViewPercentage,subscribersGained,likes,comments",filters:`video==${videoId}`});const response=await fetch(`https://youtubeanalytics.googleapis.com/v2/reports?${q}`,{headers:{Authorization:`Bearer ${await accessToken()}`}});if(!response.ok)throw new Error(`YouTube Analytics request failed (${response.status}). Reconnect YouTube to grant analytics access.`);const body=await response.json() as {rows?:number[][]};const row=body.rows?.[0]??[0,0,0,0,0,0,0];return validateSnapshot({projectId,youtubeVideoId:videoId,windowHours,source:"youtube",views:row[0],estimatedMinutesWatched:row[1],averageViewDuration:row[2],averageViewPercentage:row[3],subscribersGained:row[4],likes:row[5],comments:row[6],impressions:null,impressionCtr:null});}
export async function collectAnalytics(projectId:string,windowHours:AnalyticsWindow){const upload=getUpload(projectId),hasLiveVideo=connectionStatus().connected&&!!upload?.youtubeVideoId&&!upload.youtubeVideoId.startsWith("demo-");return process.env.ANALYTICS_PROVIDER==="youtube"||hasLiveVideo?youtube(projectId,windowHours):demo(projectId,windowHours)}
