import {randomUUID} from "node:crypto";
import {readFileSync,statSync} from "node:fs";
import {resolve} from "node:path";
import {db} from "@/infrastructure/database";
import {accessToken} from "@/infrastructure/youtube-auth";
import type {SeoPackage} from "@/domain/publishing";

export type YoutubeUpload={id:string;status:string;youtubeVideoId:string|null;bytesUploaded:number;totalBytes:number;privacyStatus:string;errorMessage:string|null;updatedAt:string};
export async function uploadPrivate(projectId:string,seo:SeoPackage,declarations:{madeForKids:boolean;containsSyntheticMedia:boolean}):Promise<YoutubeUpload>{const prior=getUpload(projectId);if(prior?.youtubeVideoId)return prior;const file=resolve("public","generated",projectId,"render","video-final.mp4"),total=statSync(file).size,now=new Date().toISOString(),id=prior?.id??randomUUID();if(process.env.PUBLISH_PROVIDER!=="youtube"){const videoId=`demo-${projectId.slice(0,8)}`;db.prepare("INSERT OR REPLACE INTO youtube_uploads VALUES (?,?, 'UPLOADED_PRIVATE',NULL,?,?,?,'private',NULL,?,?)").run(id,projectId,videoId,total,total,now,now);return getUpload(projectId)!}const token=await accessToken();if(!prior)db.prepare("INSERT INTO youtube_uploads VALUES (?,?, 'INITIALIZING',NULL,NULL,0,?,'private',NULL,?,?)").run(id,projectId,total,now,now);const init=await fetch("https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json; charset=UTF-8","X-Upload-Content-Length":String(total),"X-Upload-Content-Type":"video/mp4"},body:JSON.stringify({snippet:{title:seo.selectedTitle,description:seo.description,tags:seo.tags,categoryId:"27"},status:{privacyStatus:"private",selfDeclaredMadeForKids:declarations.madeForKids,containsSyntheticMedia:declarations.containsSyntheticMedia}})});if(!init.ok)throw new Error(`YouTube upload initialization failed (${init.status})`);const session=init.headers.get("location");if(!session)throw new Error("YouTube returned no resumable upload URL");db.prepare("UPDATE youtube_uploads SET status='UPLOADING',session_url=?,updated_at=? WHERE id=?").run(session,new Date().toISOString(),id);const put=await fetch(session,{method:"PUT",headers:{Authorization:`Bearer ${token}`,"Content-Type":"video/mp4","Content-Length":String(total)},body:readFileSync(file)});if(!put.ok)throw new Error(`YouTube upload failed (${put.status})`);const result=await put.json() as {id:string};db.prepare("UPDATE youtube_uploads SET status='UPLOADED_PRIVATE',youtube_video_id=?,bytes_uploaded=?,updated_at=? WHERE id=?").run(result.id,total,new Date().toISOString(),id);return getUpload(projectId)!;}
export function getUpload(projectId:string):YoutubeUpload|null{const r=db.prepare("SELECT * FROM youtube_uploads WHERE project_id=?").get(projectId)as Record<string,unknown>|undefined;return r?{id:r.id as string,status:r.status as string,youtubeVideoId:r.youtube_video_id as string|null,bytesUploaded:r.bytes_uploaded as number,totalBytes:r.total_bytes as number,privacyStatus:r.privacy_status as string,errorMessage:r.error_message as string|null,updatedAt:r.updated_at as string}:null;}
